ТЗ #13. add-controllers. Попытка 1
Vachagan-O/java-shareit pull request #1
Opened 2023-05-26 14:55 UTC by Vachagan-O

2023-05-26 20:33 UTC, db-exp requested changes

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +/**
давай удалим?

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (UserDto user : users) {
можно короче -  return users.stream().filter(x->x.getEmail().equals(email).findFirst().isEmpty()

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                return true;
немного нелогично - isUniqueEmail возвращает true если уникально, а тут наоборот

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    boolean isUniqueEmail(String email);
не нужен в интерфейсе - лучше его в private метод в реализации

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private String email;
еще Size можно

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +/**
давай удалим

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "У Вас нет прав на редактирование");
лучше кастомную ошибку, не нужно ошибки уровня контроллера изпользовать в бизнес-логике

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "У Вас нет прав на редактирование");
и на уровне глобального обработчика ошибок уже можно обернуть в статус

2023-05-26 20:33 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "У Вас нет прав на редактирование");
пример - https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-05-27 10:19 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (UserDto user : users) {
+

2023-05-27 10:21 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                return true;
V

2023-05-27 10:21 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    boolean isUniqueEmail(String email);
V

2023-05-27 10:23 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private String email;
V

2023-05-27 10:28 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +/**
V

2023-05-28 08:03 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +/**
V

2023-05-28 13:17 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            user.setEmail(userDto.getEmail());
вот тут ненужно ставить

2023-05-28 13:19 UTC, db-exp requested changes

2023-05-28 13:19 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Пользователь не найден");
так и осталось ResponseStatus - давай на NOT_FOUND поменяем

2023-05-28 13:19 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new RuntimeException("Пользователь с такой почтой уже существует");
лучше кастомную бросить - ValidationException, например

2023-05-28 13:50 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Пользователь не найден");
V

2023-05-28 13:52 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new RuntimeException("Пользователь с такой почтой уже существует");
V

2023-05-28 13:56 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            user.setEmail(userDto.getEmail());
V

2023-05-28 14:34 UTC, db-exp approved these changes

2023-05-29 05:17 UTC, merged