ТЗ #15. add-bookings.
Vachagan-O/java-shareit pull request #3
Opened 2023-06-26 12:31 UTC by Vachagan-O

2023-06-29 16:05 UTC, db-exp requested changes

2023-06-29 16:05 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
не хватает аннотации Repository

2023-06-29 16:05 UTC, db-exp commented on src/main/resources/application.properties
>  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
кажется настройки  Postgres'а потерялась

2023-06-29 16:05 UTC, db-exp commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void findItemsByUserId_whenUserExists_thenReturnedItems() {
давай соблюдать camelCase )

2023-06-29 16:05 UTC, db-exp commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void findItemsByUserId_whenUserExists_thenReturnedItems() {
это везде

2023-06-29 16:05 UTC, db-exp commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplIntegrationTest.java
> +    private final EntityManager em;
проще и быстрей - пользоваться репозиториями

2023-06-29 16:26 UTC, Vachagan-O commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
✅

2023-06-29 17:03 UTC, Vachagan-O commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void findItemsByUserId_whenUserExists_thenReturnedItems() {
✅

2023-06-30 08:56 UTC, db-exp approved these changes

2023-06-30 11:49 UTC, merged